name: Python

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        mcp-server: ["servers/planningmcp", "servers/templatemcp"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync
        working-directory: ${{ matrix.mcp-server }}
      - name: Lint
        run: uv run ruff check .
        working-directory: ${{ matrix.mcp-server }}
      - name: Type check
        run: uv run mypy --install-types --non-interactive .
        working-directory: ${{ matrix.mcp-server }}
      - name: Test
        run: uv run pytest -v -s --cov=src --cov-report=xml tests
        working-directory: ${{ matrix.mcp-server }}
